import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 根目錄的 layout 只處理全局設定，不包含 html 和 body
export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return children;
}
