import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlProvider } from 'next-intl';
import { useLocale } from 'next-intl';
import { useEffect } from 'react';
import "@/assets/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",  
};

export default function RootLayout({ children, params }: { children: React.ReactNode; params: { locale: string } }) {

  const locale = useLocale(); // 獲取當前語系

  useEffect(() => {
    // 動態更新 html 的 lang 屬性
    document.documentElement.lang = locale;
  }, [locale]);

  return (
    <NextIntlProvider locale={locale}>
      <html lang={locale}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </NextIntlProvider>
  );
}
